# Use the official Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /application

# Copy the requirements file to the working directory
COPY requirements.txt .

# Install the Python dependencies
RUN pip install -r requirements.txt

# Copy the application code and all the files to the working directory
COPY . /application

# # Use the official Python base image
FROM --platform=linux/amd64 ubuntu:jammy

# # Set the working directory inside the container
WORKDIR /home/nl2spec
# # Copy the application code and all the files to the working directory
COPY . /home/nl2spec

# Install the Python dependencies
RUN apt-get -q update && \
    DEBIAN_FRONTEND=noninteractive \
    apt-get -q install -y \
    python3 python3-pip vim

RUN pip3 install --upgrade pip && \
    pip3 install -r /home/nl2spec/requirements.txt

# Expose the port on which the application will run
EXPOSE 5000

# Run the FASTAPI application using the uvicorn server.
CMD ["python", "-m", "flask", "--app", "client.py", "run", "port", "5050"]