name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env: 
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        API_KEY: ${{ secrets.OPENAI_SECRET_KEY }}        
      run: docker login -u rkundula -p $DOCKER_PASS
    - name: Build a docker image
      run: docker build -t nl2ltl .
    - name: Tag a docker image
      run: docker tag nl2ltl:latest rkundula/nl2ltl:latest
    - name: Push docker image
      run: docker push rkundula/nl2ltl:latest
